# Generated by Django 3.2.5 on 2022-10-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loginactivity_logoutactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tel. Number'),
        ),
    ]
