# Generated by Django 3.2.5 on 2022-10-24 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_telephone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telephone_number',
        ),
    ]
